#jdbc설정
#인지그룹
#jdbc.driverClassName=org.mariadb.jdbc.Driver
#jdbc.jdbcUrl=jdbc:mariadb://64.110.69.79:3306/covi_smart4j?autoReconnect=true&allowMultiQueries=true&useUnicode=true
#jdbc.userName=gwuser
#jdbc.userPwd=nujsLxRTH68XnKXT

#이음톡staging
jdbc.driverClassName=org.mariadb.jdbc.Driver
jdbc.jdbcUrl=jdbc:mariadb://192.168.12.24:3306/messenger?autoReconnect=true&allowMultiQueries=true&useUnicode=true&connectionCollation=utf8mb4_unicode_ci
jdbc.userName=eumuser
jdbc.userPwd=Covi@2020

#redis
redis.host=127.0.0.1
redis.port=6379
redis.pwd=Covi@20203